name: test_via_qemu

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

  build_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build
        run: cargo bootimage --verbose

      - name: Run tests
        run: cargo test --verbose
